// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import  'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDMubKt6x-p-rMMhl19UkvKpS21OMAwVgI",
      authDomain: "emergency-system-98b14.firebaseapp.com",
      databaseURL: "https://emergency-system-98b14-default-rtdb.firebaseio.com",
      projectId: "emergency-system-98b14",
      storageBucket: "emergency-system-98b14.firebasestorage.app",
      messagingSenderId: "474966549952",
      appId: "1:474966549952:web:de8597f096f2015bc05425"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLoQfoKTgEsZnOYB3p4Xfg-wYIUypzhNw',
    appId: '1:474966549952:android:0b1db9b1b890988fc05425',
    messagingSenderId: '474966549952',
    projectId: 'emergency-system-98b14',
    databaseURL: 'https://emergency-system-98b14-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-system-98b14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTAKXAErG7GbeWN645ZZ0_pTwMJwpHCKA',
    appId: '1:474966549952:ios:024ccc00e6087f41c05425',
    messagingSenderId: '474966549952',
    projectId: 'emergency-system-98b14',
    databaseURL: 'https://emergency-system-98b14-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-system-98b14.firebasestorage.app',
    iosBundleId: 'com.example.alertSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTAKXAErG7GbeWN645ZZ0_pTwMJwpHCKA',
    appId: '1:474966549952:ios:024ccc00e6087f41c05425',
    messagingSenderId: '474966549952',
    projectId: 'emergency-system-98b14',
    databaseURL: 'https://emergency-system-98b14-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-system-98b14.firebasestorage.app',
    iosBundleId: 'com.example.alertSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMubKt6x-p-rMMhl19UkvKpS21OMAwVgI',
    appId: '1:474966549952:web:189dbe8b0cfa3bcac05425',
    messagingSenderId: '474966549952',
    projectId: 'emergency-system-98b14',
    authDomain: 'emergency-system-98b14.firebaseapp.com',
    databaseURL: 'https://emergency-system-98b14-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-system-98b14.firebasestorage.app',
  );
}
